### PR TITLE
Adding callback data attribute for re-captcha callback support

### PR DESCRIPTION
**Pull request by uniacid**
Figure I should PR this so it's not overwritten on any plugin updates accidentally as I use it on my end for verification of user response via JS callback when needed.

> Optional. The name of your callback function to be executed when the user submits a successful CAPTCHA response. The user's response, g-recaptcha-response, will be the input for your callback function.

### CODE REVIEW

**Comment by alxy** [comment]
Why exactly is this needed?

**Comment by uniacid** [comment]
Basically if you want to implement and extend verification of the captcha result with a JS callback incase you want to do extra verification handling, for example with form validation and using a validator plugin that might submit the form before the captcha is fully validated.

**Comment by uniacid** [comment]
Any update?

If you need some docs on this but it's a standard optional option allowed by recaptcha:
Example: verifyCallback
[https://developers.google.com/recaptcha/docs/display](https://developers.google.com/recaptcha/docs/display)

Can also add the expired-callback if you want to cover both callbacks, anyways I think this will help in the long run.

Let me know if you feel otherwise.

**Comment by alxy** [comment]
Ok merged this for now....

**Pull request merged**
